function ytclip --description "Download a YouTube video section to ~/Videos/ytclip/ and copy to clipboard"
    if test (count $argv) -ne 3
        echo "Usage: ytclip URL START END" >&2
        return 1
    end

    set -l url $argv[1]
    set -l start $argv[2]
    set -l end $argv[3]

    set -l output_dir "$HOME/Videos/ytclip"

    # Ensure the destination directory exists
    if not test -d "$output_dir"
        mkdir -p "$output_dir"
    end

    # Use a tracker to capture the final filename generated by yt-dlp
    set -l script_timestamp (date +%s)
    set -l path_tracker "/tmp/ytclip_path_$script_timestamp.txt"

    # Download section using an output template prefixed by a timestamp
    # Redirect yt-dlp stdout to stderr to keep stdout clean for piping/substitution
    yt-dlp -f "bv[ext=mp4]+ba[ext=m4a]/b[ext=mp4]" \
        --download-sections "*$start-$end" \
        --force-keyframes-at-cuts \
        -o "$output_dir/%(autonumber)s_%(title)s.%(ext)s" \
        --autonumber-start "$script_timestamp" \
        --exec "echo {} > $path_tracker" \
        "$url" >&2

    if test $status -ne 0
        echo "Error: Download failed." >&2
        rm -f "$path_tracker"
        return 1
    end

    # Read the exact filepath generated by yt-dlp
    set -l target (cat "$path_tracker")
    rm -f "$path_tracker"

    # text/uri-list specification requires \r\n line endings
    printf "file://%s\r\n" "$target" | wl-copy -t text/uri-list

    # Redirect informational status updates to stderr
    echo "Saved to: $target" >&2
    echo "File path copied to clipboard." >&2

    # Output ONLY the raw file path string to stdout for command substitution
    echo "$target"
end
