function ffcompress --description "Compress a video to a target size in MB and copy path to clipboard"
    set -l input ""
    set -l target_size 10

    # Parse whether input path is coming from stdin (pipe) or arguments
    if not isatty stdin
        # Path is piped in (e.g., from ytclip)
        read -l piped_input
        set input (string trim $piped_input)
        if test (count $argv) -ge 1
            set target_size $argv[1]
        end
    else
        # Path is provided as an argument
        if test (count $argv) -ge 1
            set input $argv[1]
        else
            echo "Usage: ffcompress <input_file> [target_size_mb]" >&2
            echo "   or: ytclip ... | ffcompress [target_size_mb]" >&2
            return 1
        end
        if test (count $argv) -ge 2
            set target_size $argv[2]
        end
    end

    # Verify input file existence
    if not test -f "$input"
        echo "Error: Input file '$input' does not exist." >&2
        return 1
    end

    set -l output (string replace -r '\.[^.]+$' '' $input)"_compressed.mp4"

    # Extract video duration using ffprobe
    set -l duration (ffprobe -v error -show_entries format=duration -of default=noprint_wrappers=1:nokey=1 "$input")
    if test -z "$duration"
        echo "Error: Failed to determine video duration." >&2
        return 1
    end

    set -l audio_kbps 128
    set -l total_kbps (math "floor(($target_size * 8192) / $duration)")
    set -l video_kbps (math "$total_kbps - $audio_kbps")

    if test $video_kbps -le 0
        echo "Error: Target size "$target_size"MB is too small for the video duration." >&2
        return 1
    end

    # Run 2-pass encoding
    ffmpeg -y -i "$input" -c:v libx264 -b:v "$video_kbps"k -pass 1 -an -f null /dev/null; and \
    ffmpeg -y -i "$input" -c:v libx264 -b:v "$video_kbps"k -pass 2 -c:a aac -b:a "$audio_kbps"k "$output"

    if test $status -ne 0
        echo "Error: Compression failed." >&2
        rm -f ffmpeg2pass-0.log ffmpeg2pass-0.log.mbtree
        return 1
    end

    # Clean up log files generated by ffmpeg pass 1
    rm -f ffmpeg2pass-0.log ffmpeg2pass-0.log.mbtree

    # Resolve absolute path for the clipboard URI specification
    set -l absolute_output (realpath "$output")

    # Copy to clipboard (text/uri-list specification requires \r\n line endings)
    printf "file://%s\r\n" "$absolute_output" | wl-copy -t text/uri-list

    # Print status information to stderr
    echo "Compressed file saved to: $absolute_output" >&2
    echo "Compressed file path copied to clipboard." >&2

    # Output ONLY the clean path string to stdout for downstream piping/substitution
    echo "$absolute_output"
end
