function ytclip --description "Download a YouTube video section to ~/Videos/ytclip/ and copy to clipboard"
    if test (count $argv) -ne 3
        echo "Usage: ytclip URL START END" >&2
        return 1
    end

    set -l url $argv[1]
    set -l start $argv[2]
    set -l end $argv[3]

    set -l output_dir "$HOME/Videos/ytclip"

    # Ensure the destination directory exists
    if not test -d "$output_dir"
        mkdir -p "$output_dir"
    end

    set -l script_timestamp (date +%s)
    set -l path_tracker "/tmp/ytclip_path_$script_timestamp.txt"

    # Filename ends in the requested clip range, e.g. "..._0:48-0:53.mp4"
    set -l suffix_literal (string join "" "_" $start "-" $end ".%(ext)s")

    # Budget the title's byte allowance so the FULL basename (title +
    # suffix), including temporary suffixes yt-dlp/ffmpeg append while
    # downloading (e.g. ".f398.mp4.part"), stays under the filesystem's
    # 255-byte filename limit.
    set -l suffix_bytes_estimate (printf "%s" (string join "" "_" $start "-" $end ".mp4") | wc -c)
    set -l temp_suffix_margin 20
    set -l title_budget_bytes (math --scale=0 "255 - $suffix_bytes_estimate - $temp_suffix_margin")

    # Fetch the real title so the title is trimmed to the exact number of
    # characters that fit, rather than a flat worst-case guess -- titles
    # that already fit are kept whole.
    set -l raw_title (yt-dlp --simulate --print "%(title)s" "$url" 2>/dev/null)

    set -l title_trim_len 0
    if test -z "$raw_title"
        # Metadata probe failed; fall back to a conservative worst-case
        # trim (assumes up to 4 bytes/character) so the download can
        # still proceed safely.
        set title_trim_len (math --scale=0 "$title_budget_bytes / 4")
    else
        # Binary-search the longest title prefix whose UTF-8 byte length
        # still fits the budget (titles can mix 1-4 byte/char scripts).
        set -l lo 0
        set -l hi (string length -- $raw_title)
        while test $lo -lt $hi
            set -l mid (math --scale=0 "($lo + $hi + 1) / 2")
            set -l candidate_bytes (printf "%s" (string sub -l $mid -- $raw_title) | wc -c)
            if test $candidate_bytes -le $title_budget_bytes
                set lo $mid
            else
                set hi (math --scale=0 "$mid - 1")
            end
        end
        set title_trim_len $lo
    end

    set -l title_spec (string join "" "%(title)." $title_trim_len "s")
    set -l o_template (string join "" "$output_dir/" $title_spec $suffix_literal)

    # Download section using an output template ending in the clip range
    # Redirect yt-dlp stdout to stderr to keep stdout clean for piping/substitution
    yt-dlp -4 -f "bv[ext=mp4]+ba[ext=m4a]/b[ext=mp4]" \
        --download-sections "*$start-$end" \
        --force-keyframes-at-cuts \
        -o "$o_template" \
        --exec "echo {} > $path_tracker" \
        "$url" >&2

    if test $status -ne 0
        echo "Error: Download failed." >&2
        rm -f "$path_tracker"
        return 1
    end

    # Read the exact filepath generated by yt-dlp
    set -l target (cat "$path_tracker")
    rm -f "$path_tracker"

    # text/uri-list specification requires \r\n line endings
    printf "file://%s\r\n" "$target" | wl-copy -t text/uri-list

    # Redirect informational status updates to stderr
    echo "Saved to: $target" >&2
    echo "File path copied to clipboard." >&2

    # Output ONLY the raw file path string to stdout for command substitution
    echo "$target"
end
